//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBasicListApp2.Models.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class tblBasicList
    {
        public int BasicListID { get; set; }

        [Required(ErrorMessage = "*")]
        [Display(Name = "Date of entry")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public System.DateTime InputDate { get; set; }

        [Required(ErrorMessage = "*")]
        [Display(Name = "What needs to be done?")]
        public string InputItem { get; set; }

        [Display(Name = "Priority?")]
        [RegularExpression("^[0-9]$", ErrorMessage = "Please input value between 1 and 10")]
        public int InputImportance { get; set; }

        [Display(Name = "Item Completed?")]
        public Nullable<bool> ItemCompletion { get; set; }
    }
}
