using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using MyBasicListApp2.Models.DB;

namespace MyBasicListApp2.Models.EntityManager
{
    public class ListManager
    {
        public void AddToList(tblBasicList LVM)
        {
            //Directions:
            // Firstly we create an addtolist method that will be used to update the databse table
            // In this method as a perameter we pass a "listViewModel" which is going to be used to
            // provide the cshtml form with the necessary fields to be filled out by the user.

            // After the form is filled out, the properties are get and set to the values the user
            // input in the listViewModel.
            // This listViewModel is passed into the AddToList method created in the ListManager (entity
            // Manager) class.
            // In the AddToList method I create a connection to the DAL (using). Inside of the using
            // statment I build a new List object (class generated by EF), and this new objects 
            // attibutes are set equal to the values of the viewModel filled out by the user.
            // Then the model is added and validated by the ADD method to the database context (to verify
            // the attributes are applicable), followed by saving the object to the table.

            // Next this method needs to be called by the 


            // Create database connection
            using (MyBasicListAppEntities db = new MyBasicListAppEntities())
            {
                tblBasicList TBL = new tblBasicList();
                TBL.InputDate = LVM.InputDate;
                TBL.InputItem = LVM.InputItem;
                TBL.InputImportance = LVM.InputImportance;
                TBL.ItemCompletion = LVM.ItemCompletion;

                db.tblBasicLists.Add(TBL);
                db.SaveChanges();

            }
        }
        //public void Remove(int id)
        //{
        //    MyBasicListAppEntities db = new MyBasicListAppEntities();

        //    tblBasicList objDelete = db.tblBasicLists.Find(id);
        //    db.tblBasicLists.Remove(objDelete);
        //    db.SaveChanges();
        //}
    }
}